name: 🐛 Bug Report
description: Create a bug report to help improve the project
labels: ["bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out this form as completely as possible.

  - type: input
    id: environment
    attributes:
      label: Environment
      description: What browser and version are you using?
      placeholder: "e.g., Chrome 122.0.6261.94"
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Affected Component
      description: Which component is the bug related to?
      options:
        - Game Physics
        - Network/Multiplayer
        - Input Handling
        - Rendering
        - Room Management
        - Authentication
        - Worker Communication
        - Other
    validations:
      required: true

  - type: input
    id: latency
    attributes:
      label: Network Latency
      description: If this is a multiplayer/network issue, what was your approximate latency?
      placeholder: "e.g., 50ms"
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: What happened?
      placeholder: |
        1. What did you expect to happen?
        2. What actually happened?
        3. Steps to reproduce the issue
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Log Output
      description: Please copy and paste any relevant log output or error messages
      render: shell
    validations:
      required: false

  - type: input
    id: fps
    attributes:
      label: Frame Rate
      description: What was your frame rate when the issue occurred?
      placeholder: "e.g., 60 FPS"
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
